In [4]:
                # soal nomor satu

import random

# Membuat list untuk menyimpan angka-angka acak
angka_acak = []

# Menghasilkan lima angka acak antara 1 dan 10
for _ in range(5):
    angka_acak.append(random.randint(1, 10))

# Menampilkan angka-angka acak
print("Angka-angka acak antara 1 dan 10:")
for angka in angka_acak:
    print(angka)


Angka-angka acak antara 1 dan 10:
4
2
7
6
4


In [9]:
        # soal nomor dua

import random

# Membuat tuple untuk menyimpan angka-angka acak
angka_acak = ()

# Menghasilkan lima angka acak antara 1 dan 10
for _ in range(5):
    angka_acak += (random.randint(1, 10),)

# Menampilkan angka-angka acak
print("Angka-angka acak antara 1 dan 10:")
for angka in angka_acak:
    print(angka)


Angka-angka acak antara 1 dan 10:
4
8
5
5
5


In [10]:
        # soal nomor 3

import random

# Membuat tuple awal untuk menyimpan angka-angka acak
angka_acak_awal = ()

# Menghasilkan lima angka acak antara 1 dan 10
for _ in range(5):
    angka_acak_awal += (random.randint(1, 10),)

# Menampilkan angka-angka acak awal
print("Angka-angka acak awal antara 1 dan 10:")
for angka in angka_acak_awal:
    print(angka)

# Menambahkan angka acak tambahan ke tuple
angka_acak_tambahan = ()
for _ in range(3):
    angka_acak_tambahan += (random.randint(1, 10),)

# Membuat tuple baru yang berisi angka-angka acak awal dan tambahan
angka_acak_baru = angka_acak_awal + angka_acak_tambahan

# Menampilkan angka-angka acak baru
print("\nAngka-angka acak baru (termasuk tambahan) antara 1 dan 10:")
for angka in angka_acak_baru:
    print(angka)


Angka-angka acak awal antara 1 dan 10:
9
9
1
3
1

Angka-angka acak baru (termasuk tambahan) antara 1 dan 10:
9
9
1
3
1
6
2
3


In [11]:
    # soal nomor 4

def urutkan_tuple(tuple_angka):
    # Mengubah tuple menjadi list untuk diurutkan
    list_angka = list(tuple_angka)
    # Mengurutkan list
    list_angka.sort()
    # Mengembalikan tuple hasil pengurutan
    return tuple(list_angka)

# Contoh penggunaan fungsi
tuple_angka = (9, 2, 7, 4, 5)
tuple_terurut = urutkan_tuple(tuple_angka)
print("Tuple terurut:", tuple_terurut)


Tuple terurut: (2, 4, 5, 7, 9)


In [3]:
        # soal nomor 5

import numpy as np

# Membuat array Numpy 1D dengan 5 bilangan bulat acak antara 1 dan 10
array_acak = np.random.randint(1, 11, size=5)

# Menampilkan array Numpy
print("Array Numpyy 1D dengan bilangan bulat acak antara 1 dan 10:")
print(array_acak)


Array Numpyy 1D dengan bilangan bulat acak antara 1 dan 10:
[ 9  5 10  9  3]


In [16]:
            # soal nomor 6

import numpy as np

# Array Numpy 1D dengan 5 bilangan bulat acak antara 1 dan 10
array_acak = np.random.randint(1, 11, size=5)

# Menampilkan array Numpy
print("Array Numpy 1D dengan bilangan bulat acak antara 1 dan 10:")
print(array_acak)

# Menghitung mean
mean = np.mean(array_acak)
print("Mean:", mean)

# Menghitung median
median = np.median(array_acak)
print("Median:", median)

# Menghitung standar deviasi
std_dev = np.std(array_acak)
print("Standar Deviasi:", std_dev)


Array Numpy 1D dengan bilangan bulat acak antara 1 dan 10:
[2 1 1 5 8]
Mean: 3.4
Median: 2.0
Standar Deviasi: 2.727636339397171


In [19]:
            # soal nomor 7

import numpy as np

# Membuat array NumPy 2D dengan ukuran 3x3 berisi angka acak antara 1 dan 10
array_acak_2d = np.random.randint(1, 11, size=(3, 3))

# Menampilkan array NumPy 2D
print("Array NumPy 2D (3x3) dengan angka acak antara 1 dan 10:")
print(array_acak_2d)


Array NumPy 2D (3x3) dengan angka acak antara 1 dan 10:
[[ 8  8  8]
 [ 7 10  5]
 [ 4  3  9]]


In [21]:
        # soal nomor 8

import numpy as np

# Array NumPy 2D (3x3) dengan angka acak antara 1 dan 10
array_acak_2d = np.random.randint(1, 11, size=(3, 3))

# Menampilkan array NumPy 2D
print("Array NumPy 2D (3x3) dengan angka acak antara 1 dan 10:")
print(array_acak_2d)

# Meratakan array 2D menjadi array 1D menggunakan flatten()
array_1d_flatten = array_acak_2d.flatten()

# Menampilkan array 1D yang telah diratakan
print("\nArray 1D yang telah diratakan menggunakan flatten():")
print(array_1d_flatten)

# Meratakan array 2D menjadi array 1D menggunakan ravel()
array_1d_ravel = array_acak_2d.ravel()

# Menampilkan array 1D yang telah diratakan menggunakan ravel()
print("\nArray 1D yang telah diratakan menggunakan ravel():")
print(array_1d_ravel)


Array NumPy 2D (3x3) dengan angka acak antara 1 dan 10:
[[ 6  4  1]
 [ 6  2  1]
 [ 9 10  3]]

Array 1D yang telah diratakan menggunakan flatten():
[ 6  4  1  6  2  1  9 10  3]

Array 1D yang telah diratakan menggunakan ravel():
[ 6  4  1  6  2  1  9 10  3]


In [23]:
        # soal nomor 10

import pandas as pd

# Membuat dictionary yang berisi data nama, usia, dan kota dari 3 orang
data = {
    'Nama': ['Amar', 'Jasuke', 'Piter'],
    'Usia': [25, 30, 28],
    'Kota': ['Jakarta', 'Surabaya', 'Bandung'],
    'Pekerjaan': ['Whiters', 'Joki', 'Penari latar']
}

# Membuat DataFrame dari dictionary
df = pd.DataFrame(data)

# Menampilkan DataFrame
print(df)


    Nama  Usia      Kota     Pekerjaan
0   John    25   Jakarta         Sopir
1   Anna    30  Surabaya          Joki
2  Peter    28   Bandung  Penari latar


In [24]:
        # soal nomor 11

import pandas as pd

# Membuat dictionary yang berisi data nama, usia, dan kota dari 3 orang
data = {
    'Nama': ['Amar', 'Jasuke', 'Piter'],
    'Usia': [31, 30, 28],
    'Kota': ['Jakarta', 'Surabaya', 'Bandung'],
    'Pekerjaan': ['Withers', 'Joki', 'Penari latar']
}

# Membuat DataFrame dari dictionary
df = pd.DataFrame(data)

# Menampilkan DataFrame
print(df)


     Nama  Usia      Kota     Pekerjaan
0    Amar    31   Jakarta         Sopir
1  Jasuke    30  Surabaya          Joki
2   Piter    28   Bandung  Penari latar


In [25]:
        # soal nomor 12

import pandas as pd

# Membuat DataFrame yang sama seperti sebelumnya
data = {
    'Nama': ['Amar', 'Jasuke', 'Piter'],
    'Usia': [31, 30, 28],
    'Kota': ['Jakarta', 'Surabaya', 'Bandung'],
    'Pekerjaan': ['Whiters', 'Joki', 'Penari latar']
}
df = pd.DataFrame(data)

# Mengurutkan DataFrame berdasarkan kolom 'Usia' dari yang muda ke yang tua
df_urut = df.sort_values(by='Usia')

# Menampilkan DataFrame yang telah diurutkan
print("DataFrame yang diurutkan berdasarkan usia:")
print(df_urut)


DataFrame yang diurutkan berdasarkan usia:
     Nama  Usia      Kota     Pekerjaan
2   Piter    28   Bandung  Penari latar
1  Jasuke    30  Surabaya          Joki
0    Amar    31   Jakarta         Sopir
